// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMWrEKryrN76dZ-5hoPCO97wYEjO1bVM',
    appId: '1:666196985301:web:a8e5d0d9f7cd09f379a95c',
    messagingSenderId: '666196985301',
    projectId: 'iotdemo-8246c',
    authDomain: 'iotdemo-8246c.firebaseapp.com',
    databaseURL: 'https://iotdemo-8246c-default-rtdb.firebaseio.com',
    storageBucket: 'iotdemo-8246c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgUvklMRPt2_Qw2C1TPkekK-v8VrGgrnA',
    appId: '1:666196985301:android:2f2ae8ce6083689e79a95c',
    messagingSenderId: '666196985301',
    projectId: 'iotdemo-8246c',
    databaseURL: 'https://iotdemo-8246c-default-rtdb.firebaseio.com',
    storageBucket: 'iotdemo-8246c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbl73ZhBl7WRocbclLYbVc1kfR16j7Jbw',
    appId: '1:666196985301:ios:bb350a00673c07e979a95c',
    messagingSenderId: '666196985301',
    projectId: 'iotdemo-8246c',
    databaseURL: 'https://iotdemo-8246c-default-rtdb.firebaseio.com',
    storageBucket: 'iotdemo-8246c.appspot.com',
    iosBundleId: 'com.example.demo',
  );

}